Add Standard Tools to PHP Image

diff --git a/images/php/Dockerfile b/images/php/Dockerfile
--- a/images/php/Dockerfile
+++ b/images/php/Dockerfile
@@ -47,11 +47,26 @@ RUN    apk add --no-cache --virtual .event-build-deps \
     && echo "extension=event.so" > /usr/local/etc/php/conf.d/pecl-event.ini \
     && apk del .event-build-deps
 
-RUN apk add --no-cache --virtual .xdebug-build-deps $PHPIZE_DEPS \
+RUN    apk add --no-cache --virtual .xdebug-build-deps $PHPIZE_DEPS \
     && pecl install xdebug \
     && touch /usr/local/etc/php/conf.d/pecl-xdebug.ini \
     && echo ";zend_extension=xdebug.so" > /usr/local/etc/php/conf.d/pecl-xdebug.ini \
     && apk del .xdebug-build-deps
+
+# Install Composer
+RUN    curl "https://getcomposer.org/installer" -o "/tmp/composer-setup.php" \
+    && EXPECTED_SIGNATURE="$(curl https://composer.github.io/installer.sig)" \
+       ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', '/tmp/composer-setup.php');")" \
+       [ "${EXPECTED_SIGNATURE}" == "${ACTUAL_SIGNATURE}" ] || (echo  >&2 'ERROR: Invalid Composer installer signature'; exit 1;) \
+    && php "/tmp/composer-setup.php" --install-dir="/usr/local/bin" --filename="composer" \
+    && rm "/tmp/composer-setup.php"
+
+# Install PHPUnit
+RUN    curl "https://phar.phpunit.de/phpunit-5.7.phar" -o "/usr/local/bin/phpunit5" \
+    && chmod +x "/usr/local/bin/phpunit5" \
+    && curl "https://phar.phpunit.de/phpunit-6.0.phar" -o "/usr/local/bin/phpunit6" \
+    && chmod +x "/usr/local/bin/phpunit6" \
+    && ln -s "/usr/local/bin/phpunit5" "/usr/local/bin/phpunit"
 
 CMD [ "php-fpm", "--allow-to-run-as-root", "--nodaemonize" ]
 
